title: Tisza Genomics Lab
description: Exploring microbial and viral genomics through computational approaches
theme: jekyll-theme-minimal
baseurl: "/tisza-genomics-lab"
url: "https://mtisza1.github.io"

# Social/Academic Links
github_username: mtisza1
# Add other social links as needed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
