title: Tisza Genomics Lab
description: Using microbial and viral genomics to generate and test hypotheses
remote_theme: pages-themes/minimal@v0.2.0
baseurl: "/tisza-genomics-lab"
url: "https://mtisza1.github.io"
logo: /assets/images/ghost-vir.png

# Social Links
github:
  username: mtisza1
  is_project_page: true
  repository_url: https://github.com/mtisza1/tisza-genomics-lab

# Author Info
author:
  name: Mike Tisza
  links:
    - label: GitHub
      url: https://github.com/mtisza1
    - label: Google Scholar
      url: https://scholar.google.com/citations?user=qvM2fAYAAAAJ&hl=en
    - label: Twitter
      url: https://twitter.com/MikeTisza
    - label: ORCID
      url: https://orcid.org/0000-0003-1168-1617

# Institution Information
institution:
  name: "Baylor College of Medicine"
  department: "Molecular Virology and Microbiology"
  location: "Houston, TX, USA"

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
