title: Tisza Genomics Lab
description: Using microbial and viral genomics to generate and test hypotheses
theme: jekyll-theme-minimal
baseurl: "/tisza-genomics-lab"
url: "https://mtisza1.github.io"
github_username: mtisza1

colors:
  - primary: "#D3DDDC"
  - secondary: "#446455"
sidebar:
  - logo: /assets/images/ghost-vir.png

  - social_links
  children:
    - github: mtisza1
    - google_scholar: https://scholar.google.com/citations?user=qvM2fAYAAAAJ&hl=en
    - twitter: MikeTisza
    - orcid: 0000-0003-1168-1617

  - institution
  children:
    - name: "Baylor College of Medicine"
    - department: "Molecular Virology and Microbiology"
    - location: "Houston, TX, USA"
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
